APP_NAME = "Jain AI"
DEFAULT_FLASK_SECRET_KEY = "jain-ai-dev-secret-key-change-this"
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 5000
DEFAULT_LOG_LEVEL = "INFO"
TEXT_MODEL = "openai/gpt-oss-120b"
VISION_MODEL = "meta-llama/llama-4-scout-17b-16e-instruct"
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
SESSION_CHAT_KEY = "chat_history"
SESSION_LAST_ACTIVITY_KEY = "last_activity_ts"
MAX_SESSION_MESSAGES = 200
MAX_SESSION_CONTEXT_MESSAGES = 20
SESSION_TIMEOUT_MINUTES = 30
MAX_FILE_SIZE_MB = 12
DEFAULT_MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
MAX_CONTEXT_CHARS = 12000
SIMILARITY_K = 6
KEYWORD_LIMIT = 5
ALLOWED_EXTENSIONS = {".pdf", ".png", ".jpg", ".jpeg", ".webp", ".bmp"}
IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".bmp"}
PDF_EXTENSIONS = {".pdf"}
